### ISSUE TITLE
Doesn't work with FF 18

### ISSUE THREAD

**Issue by artlantis** [paulrouget/firefox-jsterm#32] opened 2013-01-15 21:14 UTC
I installed on FF 18 edition but the console screen empty as well as can't write something.

**Comment by blissdev** [comment] 2013-01-20 03:30
This is a duplicate of #31. Seems like dev responsiveness is a bit slow at the moment. I've started to look at the issue, but I'm a bit out of my depth.

**Comment by artlantis** [comment] 2013-01-20 15:13
Same issue, but button bar doesn't show in FF18 as well!

**Closed as completed** 2013-01-22 09:44 UTC
